/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme.smena;

import controller.ControllerClient;
import java.time.LocalTime;
import javax.swing.JOptionPane;
import model.Smena;

/**
 *
 * @author Administrator
 */
public class UbaciSmenuForma extends javax.swing.JFrame {

    /**
     * Creates new form UbaciSmenuForma
     */
    public UbaciSmenuForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNaziv = new javax.swing.JTextField();
        jTextFieldVremeOd = new javax.swing.JTextField();
        jTextFieldVremeDo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonUbaci = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv:");

        jLabel2.setText("Vreme od:");

        jLabel3.setText("Vreme do:");

        jButtonUbaci.setText("Ubaci");
        jButtonUbaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbaciActionPerformed(evt);
            }
        });

        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonUbaci)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(jButtonOdustani))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldVremeDo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldVremeOd)
                            .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVremeOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVremeDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUbaci)
                    .addComponent(jButtonOdustani))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jButtonUbaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbaciActionPerformed
        try {
            String naziv = jTextFieldNaziv.getText().trim();
            String vremeOdString = jTextFieldVremeOd.getText().trim();
            String vremeDoString = jTextFieldVremeDo.getText().trim();

            validiraj(naziv, vremeOdString, vremeDoString);

            LocalTime vremeOd = LocalTime.parse(vremeOdString);
            LocalTime vremeDo = LocalTime.parse(vremeDoString);

            Smena smena = new Smena(null, naziv, vremeOd, vremeDo);
            ControllerClient.getInstance().ubaciSmenu(smena);
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio smenu!", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonUbaciActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonUbaci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldNaziv;
    private javax.swing.JTextField jTextFieldVremeDo;
    private javax.swing.JTextField jTextFieldVremeOd;
    // End of variables declaration//GEN-END:variables

    private void validiraj(String naziv, String vremeOd, String vremeDo) throws Exception {
        String error = "";
    
        if (naziv.isEmpty()) {
            error += "Naziv smene ne moze biti prazan!\n";
        }
        if (vremeOd.isEmpty()) {
            error += "Vreme pocetka ne moze biti prazno!\n";
        } else {
            try {
                LocalTime.parse(vremeOd);
            } catch (Exception e) {
                error += "Vreme pocetka mora biti u formatu HH:mm!\n";
            }
        }
        if (vremeDo.isEmpty()) {
            error += "Vreme kraja ne moze biti prazno!\n";
        } else {
            try {
                LocalTime.parse(vremeDo);
            } catch (Exception e) {
                error += "Vreme kraja mora biti u formatu HH:mm!\n";
            }
        }

        if (!error.isEmpty()) {
            throw new Exception(error);
        }
    }
}
