/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme.penjac;

import controller.ControllerClient;
import forme.ModForme;
import java.util.List;
import javax.swing.JOptionPane;
import model.Kategorija;
import model.Penjac;
import modeli.ModelTabelePenjac;

/**
 *
 * @author Administrator
 */
public class PrikaziPenjacForma extends javax.swing.JFrame {

    /**
     * Creates new form PrikaziPenjacForma
     */
    public PrikaziPenjacForma() {
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePenjaci = new javax.swing.JTable();
        jButtonkreirajNovogPenjaca = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jComboBoxKategorija = new javax.swing.JComboBox<>();
        jButtonPretrazi = new javax.swing.JButton();
        jButtonPromeniPenjaca = new javax.swing.JButton();
        jButtonObrisiPenjaca = new javax.swing.JButton();
        jButtonNazad = new javax.swing.JButton();
        jButtonPrikaziSve = new javax.swing.JButton();
        jButtonkreirajDetaljiPenjaca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTablePenjaci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePenjaci);

        jButtonkreirajNovogPenjaca.setText("Kreiraj novog penjaca");
        jButtonkreirajNovogPenjaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonkreirajNovogPenjacaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o penjacu:"));
        jPanel1.setName(""); // NOI18N

        jLabel1.setText("Ime:");

        jLabel2.setText("Prezime:");

        jLabel5.setText("Kategorija:");

        jComboBoxKategorija.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(jTextFieldIme))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonPretrazi.setText("Pretrazi");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });

        jButtonPromeniPenjaca.setText("Promeni penjaca");
        jButtonPromeniPenjaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromeniPenjacaActionPerformed(evt);
            }
        });

        jButtonObrisiPenjaca.setText("Obrisi penjaca");
        jButtonObrisiPenjaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiPenjacaActionPerformed(evt);
            }
        });

        jButtonNazad.setText("Nazad");
        jButtonNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazadActionPerformed(evt);
            }
        });

        jButtonPrikaziSve.setText("Prikazi sve");
        jButtonPrikaziSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziSveActionPerformed(evt);
            }
        });

        jButtonkreirajDetaljiPenjaca.setText("Detalji penjaca");
        jButtonkreirajDetaljiPenjaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonkreirajDetaljiPenjacaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonPrikaziSve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonPretrazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonkreirajDetaljiPenjaca, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonkreirajNovogPenjaca, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPromeniPenjaca, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonObrisiPenjaca, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNazad, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButtonPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPrikaziSve, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonkreirajNovogPenjaca)
                    .addComponent(jButtonPromeniPenjaca)
                    .addComponent(jButtonObrisiPenjaca)
                    .addComponent(jButtonNazad)
                    .addComponent(jButtonkreirajDetaljiPenjaca))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonkreirajNovogPenjacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonkreirajNovogPenjacaActionPerformed
        DodajPromeniPenjacForma dppf = new DodajPromeniPenjacForma(this, null, ModForme.DODAJ);
        dppf.setVisible(true);
    }//GEN-LAST:event_jButtonkreirajNovogPenjacaActionPerformed

    private void jButtonPromeniPenjacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromeniPenjacaActionPerformed
        int selektovaniRed = jTablePenjaci.getSelectedRow();
        if (selektovaniRed ==  -1) {
            JOptionPane.showMessageDialog(this, "Penjac za izmenu nije odabran!", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ModelTabelePenjac mtp = (ModelTabelePenjac) jTablePenjaci.getModel();
        Penjac p = mtp.getPenjaci().get(selektovaniRed);
        try {
            DodajPromeniPenjacForma dppf = new DodajPromeniPenjacForma(this, p, ModForme.IZMENI);
            JOptionPane.showMessageDialog(this, "Sistem je nasao penjaca!", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
            dppf.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje penjaca!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPromeniPenjacaActionPerformed

    private void jButtonNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazadActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonNazadActionPerformed

    private void jButtonObrisiPenjacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiPenjacaActionPerformed
        int selektovaniRed = jTablePenjaci.getSelectedRow();
        if (selektovaniRed ==  -1) {
            JOptionPane.showMessageDialog(this, "Penjac za brisanje nije odabran!", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ModelTabelePenjac mtp = (ModelTabelePenjac) jTablePenjaci.getModel();
        Penjac p = mtp.getPenjaci().get(selektovaniRed);
        try {
            DodajPromeniPenjacForma dppf = new DodajPromeniPenjacForma(this, p, ModForme.OBRISI);
            JOptionPane.showMessageDialog(this, "Sistem je nasao penjaca!", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
            dppf.setVisible(true);
//            ControllerClient.getInstance().obrisiPenjaca(p);
//            JOptionPane.showMessageDialog(this, "Sistem je obrisao penjaca!", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
//            popuniTabelu();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise penjaca!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonObrisiPenjacaActionPerformed

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
        try {
            String ime = jTextFieldIme.getText().trim();
            String prezime = jTextFieldPrezime.getText().trim();
            Kategorija k = (Kategorija) jComboBoxKategorija.getSelectedItem();

            Penjac p = new Penjac();
            p.setIme(ime);
            p.setPrezime(prezime);
            p.setKategorija(k);

            List<Penjac> penjaci = ControllerClient.getInstance().pretraziPenjace(p);
            
            ModelTabelePenjac mtp = new ModelTabelePenjac(penjaci);
            jTablePenjaci.setModel(mtp);
            
            JOptionPane.showMessageDialog(this, "Sistem je nasao penjace po zadatim kriterijumima!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButtonPrikaziSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziSveActionPerformed
        jTextFieldIme.setText("");
        jTextFieldPrezime.setText("");
        jComboBoxKategorija.setSelectedIndex(-1);
        popuniTabelu();
    }//GEN-LAST:event_jButtonPrikaziSveActionPerformed

    private void jButtonkreirajDetaljiPenjacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonkreirajDetaljiPenjacaActionPerformed
        int selektovaniRed = jTablePenjaci.getSelectedRow();
        if (selektovaniRed ==  -1) {
            JOptionPane.showMessageDialog(this, "Penjac nije odabran!", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        ModelTabelePenjac mtp = (ModelTabelePenjac) jTablePenjaci.getModel();
        Penjac p = mtp.getPenjaci().get(selektovaniRed);
        
        try {
            DodajPromeniPenjacForma dppf = new DodajPromeniPenjacForma(this, p, ModForme.DETALJAN_PRIKAZ);
            JOptionPane.showMessageDialog(this, "Sistem je nasao penjaca!", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
            dppf.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje penjaca!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonkreirajDetaljiPenjacaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JButton jButtonObrisiPenjaca;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JButton jButtonPrikaziSve;
    private javax.swing.JButton jButtonPromeniPenjaca;
    private javax.swing.JButton jButtonkreirajDetaljiPenjaca;
    private javax.swing.JButton jButtonkreirajNovogPenjaca;
    private javax.swing.JComboBox<Object> jComboBoxKategorija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePenjaci;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    // End of variables declaration//GEN-END:variables

    public void prepareView() {
        try {
            jComboBoxKategorija.removeAllItems();
            List<Kategorija> kategorije = ControllerClient.getInstance().vratiKategorije();
            for (Kategorija k : kategorije) {
                jComboBoxKategorija.addItem(k);
            }
            jComboBoxKategorija.setSelectedIndex(-1);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
        
        popuniTabelu();
    }

    private void popuniTabelu() {
        try {
            List<Penjac> penjaci = ControllerClient.getInstance().vratiPenjace();
            ModelTabelePenjac mtp = new ModelTabelePenjac(penjaci);
            jTablePenjaci.setModel(mtp);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }
}
