/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme.racun;

import controller.ControllerClient;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Penjac;
import model.Racun;
import model.StavkaRacuna;
import model.Usluga;
import model.Zaposleni;
import modeli.ModelTabeleStavkaRacuna;

/**
 *
 * @author Administrator
 */
public class DodajPromeniRacunForma extends javax.swing.JFrame {
    private Racun r;
    private List<StavkaRacuna> stavkeRacuna = new ArrayList<>();
    /**
     * Creates new form DodajPromeniRacunForma
     */
    public DodajPromeniRacunForma(Racun r) {
        initComponents();
        this.r = r;
        if(r != null){
            stavkeRacuna = r.getStavkeRacuna();
        }
        prepareView();
        if(r != null){
            popuniPolja();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxZaposleni = new javax.swing.JComboBox<>();
        jComboBoxPenjac = new javax.swing.JComboBox<>();
        jTextFieldDatumIVreme = new javax.swing.JTextField();
        jTextFieldUkupanIznos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStavkeRacuna = new javax.swing.JTable();
        jButtonObrisiStavku = new javax.swing.JButton();
        jButtonSacuvaj = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxUsluge = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldKolicina = new javax.swing.JTextField();
        jButtonDodajStavku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o racunu:"));

        jLabel1.setText("Zaposleni:");

        jLabel2.setText("Penjac:");

        jLabel3.setText("Datum i vreme: ");

        jLabel4.setText("Ukupan iznos:");

        jComboBoxZaposleni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxPenjac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxZaposleni, 0, 255, Short.MAX_VALUE)
                    .addComponent(jComboBoxPenjac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldDatumIVreme)
                    .addComponent(jTextFieldUkupanIznos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxPenjac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDatumIVreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTableStavkeRacuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableStavkeRacuna);

        jButtonObrisiStavku.setText("Obrisi stavku");
        jButtonObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiStavkuActionPerformed(evt);
            }
        });

        jButtonSacuvaj.setText("Sacuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dodaj stavku:"));

        jLabel5.setText("Usluga:");

        jComboBoxUsluge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Kolicina:");

        jButtonDodajStavku.setText("Dodaj stavku");
        jButtonDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajStavkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxUsluge, 0, 184, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldKolicina))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonDodajStavku)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDodajStavku))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSacuvaj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonObrisiStavku)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonObrisiStavku)))
                .addGap(14, 14, 14)
                .addComponent(jButtonSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajStavkuActionPerformed
        Usluga usluga = (Usluga) jComboBoxUsluge.getSelectedItem();
        String kolicina = jTextFieldKolicina.getText().trim();
        
        try {
            validirajStavku(usluga, kolicina);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        StavkaRacuna sr = new StavkaRacuna(r, Integer.parseInt(kolicina), usluga);
        stavkeRacuna.add(sr);
        
        popuniTabeluStavki();
        jComboBoxUsluge.setSelectedIndex(-1);
        jTextFieldKolicina.setText("");  
    }//GEN-LAST:event_jButtonDodajStavkuActionPerformed

    private void jButtonObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiStavkuActionPerformed
        int red = jTableStavkeRacuna.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Nijedna stavka nije odabrana!", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        stavkeRacuna.remove(red);
        popuniTabeluStavki();
    }//GEN-LAST:event_jButtonObrisiStavkuActionPerformed

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        try {
            Zaposleni z = (Zaposleni) jComboBoxZaposleni.getSelectedItem();
            Penjac p = (Penjac) jComboBoxPenjac.getSelectedItem();

            validirajRacun(z, p);

            

            if (r == null) {
                Racun racun = new Racun();
                racun.setZaposleni(z);
                racun.setPenjac(p);
                racun.setDatumVreme(LocalDateTime.now());
                racun.setStavkeRacuna(stavkeRacuna);
                racun.izracunajUkupanIznos();
                ControllerClient.getInstance().kreirajRacun(racun);
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio racun!", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                r.setZaposleni(z);
                r.setPenjac(p);
                r.setDatumVreme(LocalDateTime.now());
                r.setStavkeRacuna(stavkeRacuna);
                r.izracunajUkupanIznos();
                ControllerClient.getInstance().izmeniRacun(r);
                JOptionPane.showMessageDialog(this, "Sistem je promenio racun!", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
            }

            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajStavku;
    private javax.swing.JButton jButtonObrisiStavku;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JComboBox<Object> jComboBoxPenjac;
    private javax.swing.JComboBox<Object> jComboBoxUsluge;
    private javax.swing.JComboBox<Object> jComboBoxZaposleni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStavkeRacuna;
    private javax.swing.JTextField jTextFieldDatumIVreme;
    private javax.swing.JTextField jTextFieldKolicina;
    private javax.swing.JTextField jTextFieldUkupanIznos;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        try {
            jComboBoxZaposleni.removeAllItems();
            List<Zaposleni> zaposleni = ControllerClient.getInstance().vratiZaposlene();
            for (Zaposleni z : zaposleni) {
                jComboBoxZaposleni.addItem(z);
            }
            jComboBoxZaposleni.setSelectedIndex(-1);

            jComboBoxPenjac.removeAllItems();
            List<Penjac> penjaci = ControllerClient.getInstance().vratiPenjace();
            for (Penjac p : penjaci) {
                jComboBoxPenjac.addItem(p);
            }
            jComboBoxPenjac.setSelectedIndex(-1);
            
            jComboBoxUsluge.removeAllItems();
            List<Usluga> usluge = ControllerClient.getInstance().vratiUsluge();
            for (Usluga u : usluge) {
                jComboBoxUsluge.addItem(u);
            }
            jComboBoxUsluge.setSelectedIndex(-1);
            
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm");
            jTextFieldDatumIVreme.setText(LocalDateTime.now().format(formatter));
            
            jTextFieldUkupanIznos.setEditable(false);
            jTextFieldDatumIVreme.setEditable(false);
            popuniTabeluStavki();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void popuniPolja() {
        jComboBoxZaposleni.setSelectedItem(r.getZaposleni());
        jComboBoxPenjac.setSelectedItem(r.getPenjac());

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm");
        jTextFieldDatumIVreme.setText(r.getDatumVreme().format(formatter));

        jTextFieldUkupanIznos.setText(String.valueOf(r.getUkupanIznos()));
        
        popuniTabeluStavki();
        jTextFieldDatumIVreme.setEditable(true);
    }

    private void popuniTabeluStavki() {
        ModelTabeleStavkaRacuna mts = new ModelTabeleStavkaRacuna(stavkeRacuna);
        jTableStavkeRacuna.setModel(mts);
        
        Racun racun = new Racun();
        racun.setStavkeRacuna(stavkeRacuna);
        racun.izracunajUkupanIznos();
        jTextFieldUkupanIznos.setText(String.valueOf(racun.getUkupanIznos()));
    }

    private void validirajStavku(Usluga usluga, String kolicina) throws Exception {
        String error = "";

        if (usluga == null) {
            error += "Nijedna usluga nije odabrana!\n";
        }

        if (kolicina.isEmpty()) {
            error += "Polje kolicina ne moze biti prazno!\n";
        } else {
            try {
                int kol = Integer.parseInt(kolicina);
                if (kol <= 0) {
                    error += "Kolicina mora biti pozitivan broj!\n";
                }
            } catch (NumberFormatException e) {
                error += "Kolicina mora biti ceo broj!\n";
            }
        }

        if (!error.isEmpty()) {
            throw new Exception(error);
        }
    }

    private void validirajRacun(Zaposleni z, Penjac p) throws Exception {
        String error = "";
    
        if (z == null) {
            error += "Morate odabrati zaposlenog!\n";
        }
        if (p == null) {
            error += "Morate odabrati penjaca!\n";
        }
        if (stavkeRacuna.isEmpty()) {
            error += "Racun mora imati bar jednu stavku!\n";
        }

        if (!error.isEmpty()) {
            throw new Exception(error);
        }
    }
}
