/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme.racun;

import controller.ControllerClient;
import java.util.List;
import javax.swing.JOptionPane;
import model.Penjac;
import model.Racun;
import model.Zaposleni;
import modeli.ModelTabeleRacuni;

/**
 *
 * @author Administrator
 */
public class PrikazRacunForma extends javax.swing.JFrame {

    /**
     * Creates new form PrikazRacunForma
     */
    public PrikazRacunForma() {
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRacuni = new javax.swing.JTable();
        jButtonPromeniRacun = new javax.swing.JButton();
        jButtonKreirajRacun = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxZaposleni = new javax.swing.JComboBox<>();
        jComboBoxPenjac = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonPretrazi = new javax.swing.JButton();
        jButtonPrikaziSve = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();
        jButtonDetaljiRacuna = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableRacuni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRacuni);

        jButtonPromeniRacun.setText("Promeni racun");
        jButtonPromeniRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromeniRacunActionPerformed(evt);
            }
        });

        jButtonKreirajRacun.setText("Kreiraj novi racun");
        jButtonKreirajRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajRacunActionPerformed(evt);
            }
        });

        jLabel1.setText("Zaposleni:");

        jComboBoxZaposleni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxPenjac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Penjac:");

        jButtonPretrazi.setText("Pretrazi");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });

        jButtonPrikaziSve.setText("Prikazi sve");
        jButtonPrikaziSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziSveActionPerformed(evt);
            }
        });

        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        jButtonDetaljiRacuna.setText("Detalji racuna");
        jButtonDetaljiRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetaljiRacunaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxZaposleni, 0, 213, Short.MAX_VALUE)
                            .addComponent(jComboBoxPenjac, 0, 213, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonPretrazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPrikaziSve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonDetaljiRacuna)
                                .addGap(97, 97, 97)
                                .addComponent(jButtonKreirajRacun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonPromeniRacun)
                                .addGap(129, 129, 129)
                                .addComponent(jButtonOdustani)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPretrazi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPenjac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonPrikaziSve))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPromeniRacun)
                    .addComponent(jButtonKreirajRacun)
                    .addComponent(jButtonOdustani)
                    .addComponent(jButtonDetaljiRacuna))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPromeniRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromeniRacunActionPerformed
        int selektovaniRed = jTableRacuni.getSelectedRow();
        if (selektovaniRed == -1) {
            JOptionPane.showMessageDialog(this, "Racun za promenu nije izabran!", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ModelTabeleRacuni mtr = (ModelTabeleRacuni) jTableRacuni.getModel();
        Racun r = mtr.getRacuni().get(selektovaniRed);
        try{
            DodajPromeniRacunForma dprf = new DodajPromeniRacunForma(this, r);
            JOptionPane.showMessageDialog(this, "Sistem je nasao racun!", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
            dprf.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje racun!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPromeniRacunActionPerformed

    private void jButtonKreirajRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajRacunActionPerformed
        DodajPromeniRacunForma dprf = new DodajPromeniRacunForma(this, null);
        dprf.setVisible(true);
    }//GEN-LAST:event_jButtonKreirajRacunActionPerformed

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
         try {
            Zaposleni z = (Zaposleni) jComboBoxZaposleni.getSelectedItem();
            Penjac p = (Penjac) jComboBoxPenjac.getSelectedItem();
            
            Racun r = new Racun();
            r.setZaposleni(z);
            r.setPenjac(p);

            List<Racun> racuni = ControllerClient.getInstance().pretraziRacune(r);
            
            ModelTabeleRacuni mtr = new ModelTabeleRacuni(racuni);
            jTableRacuni.setModel(mtr);
            
            JOptionPane.showMessageDialog(this, "Sistem je nasao racune po zadatim kriterijumima!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButtonPrikaziSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziSveActionPerformed
        jComboBoxZaposleni.setSelectedIndex(-1);
        jComboBoxPenjac.setSelectedIndex(-1);
        popuniTabelu();
    }//GEN-LAST:event_jButtonPrikaziSveActionPerformed

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jButtonDetaljiRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetaljiRacunaActionPerformed
        int selektovaniRed = jTableRacuni.getSelectedRow();
        if (selektovaniRed == -1) {
            JOptionPane.showMessageDialog(this, "Racun nije odabran!", "Greska!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        ModelTabeleRacuni mtr = (ModelTabeleRacuni) jTableRacuni.getModel();
        Racun r = mtr.getRacuni().get(selektovaniRed);
        
        try {
            JOptionPane.showMessageDialog(this, "Sistem je nasao racun!", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
            DetaljiRacunaForma drf = new DetaljiRacunaForma(r);
            drf.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje racun!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDetaljiRacunaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetaljiRacuna;
    private javax.swing.JButton jButtonKreirajRacun;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JButton jButtonPrikaziSve;
    private javax.swing.JButton jButtonPromeniRacun;
    private javax.swing.JComboBox<Object> jComboBoxPenjac;
    private javax.swing.JComboBox<Object> jComboBoxZaposleni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRacuni;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        try {
            jComboBoxZaposleni.removeAllItems();
            List<Zaposleni> zaposleni = ControllerClient.getInstance().vratiZaposlene();
            for (Zaposleni z : zaposleni) {
                jComboBoxZaposleni.addItem(z);
            }
            jComboBoxZaposleni.setSelectedIndex(-1);

            jComboBoxPenjac.removeAllItems();
            List<Penjac> penjaci = ControllerClient.getInstance().vratiPenjace();
            for (Penjac p : penjaci) {
                jComboBoxPenjac.addItem(p);
            }
            jComboBoxPenjac.setSelectedIndex(-1);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
        popuniTabelu();
    }

    public void popuniTabelu() {
        try {
            List<Racun> racuni = ControllerClient.getInstance().vratiRacune();
            ModelTabeleRacuni mtr = new ModelTabeleRacuni(racuni);
            jTableRacuni.setModel(mtr);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }
}
