/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import controller.ControllerClient;
import forme.penjac.PrikaziPenjacForma;
import forme.racun.PrikazRacunForma;
import forme.smena.UbaciSmenuForma;



/**
 *
 * @author Administrator
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        jLabelImeZaposleni.setText(ControllerClient.getInstance().getUlogovani().getIme());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelImeZaposleni = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRacun = new javax.swing.JMenu();
        jMenuItemPrikaziRacun = new javax.swing.JMenuItem();
        jMenuPenjac = new javax.swing.JMenu();
        jMenuItemPrikaziPenjac = new javax.swing.JMenuItem();
        jMenuSmena = new javax.swing.JMenu();
        jMenuItemUbaciSmena = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Dobrodosli, ");

        jLabelImeZaposleni.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelImeZaposleni.setText("jLabel2");

        jMenuRacun.setText("Racun");

        jMenuItemPrikaziRacun.setText("Prikazi");
        jMenuItemPrikaziRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikaziRacunActionPerformed(evt);
            }
        });
        jMenuRacun.add(jMenuItemPrikaziRacun);

        jMenuBar1.add(jMenuRacun);

        jMenuPenjac.setText("Penjac");

        jMenuItemPrikaziPenjac.setText("Prikazi");
        jMenuItemPrikaziPenjac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikaziPenjacActionPerformed(evt);
            }
        });
        jMenuPenjac.add(jMenuItemPrikaziPenjac);

        jMenuBar1.add(jMenuPenjac);

        jMenuSmena.setText("Smena");

        jMenuItemUbaciSmena.setText("Ubaci");
        jMenuItemUbaciSmena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUbaciSmenaActionPerformed(evt);
            }
        });
        jMenuSmena.add(jMenuItemUbaciSmena);

        jMenuBar1.add(jMenuSmena);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImeZaposleni)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelImeZaposleni))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPrikaziRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikaziRacunActionPerformed
        PrikazRacunForma prf = new PrikazRacunForma();
        prf.setVisible(true);
    }//GEN-LAST:event_jMenuItemPrikaziRacunActionPerformed

    private void jMenuItemPrikaziPenjacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikaziPenjacActionPerformed
        PrikaziPenjacForma ppf = new PrikaziPenjacForma();
        ppf.setVisible(true);
    }//GEN-LAST:event_jMenuItemPrikaziPenjacActionPerformed

    private void jMenuItemUbaciSmenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUbaciSmenaActionPerformed
        UbaciSmenuForma usf = new UbaciSmenuForma();
        usf.setVisible(true);
    }//GEN-LAST:event_jMenuItemUbaciSmenaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImeZaposleni;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemPrikaziPenjac;
    private javax.swing.JMenuItem jMenuItemPrikaziRacun;
    private javax.swing.JMenuItem jMenuItemUbaciSmena;
    private javax.swing.JMenu jMenuPenjac;
    private javax.swing.JMenu jMenuRacun;
    private javax.swing.JMenu jMenuSmena;
    // End of variables declaration//GEN-END:variables
}
